version: '3.2'

services:
  backend:
    container_name: backend
    build: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - ${PORT}:${PORT}
    env_file:
      - ./.env
  mongo:
    restart: always
    image: mongo:7.0.5
    volumes:
      - ./data:/data/db
    expose:
      - 27017